import Foundation

let events = [
    Event(time: "1,000",
          info: "The SNAP-10A nuclear satellite, launched in 1965 to an orbit 700 km (430 mi) above Earth, will return to the surface.",
          category: .astronomy),
    Event(time: "3015 CE",
          info: "A camera placed by Jonathon Keats will finish its exposure time after its placement at the ASU Art Museum in Tempe, Arizona, in 2015.",
          category: .technology),
    Event(time: "3183 CE",
          info: "The Time Pyramid, a public art work at Wemding, Germany, is scheduled for completion.",
          category: .technology),
    Event(time: "6939 CE",
          info: "The Westinghouse Time Capsules from the years 1939 and 1964 are scheduled to be opened.",
          category: .technology),
    Event(time: "7000 CE",
          info: "The last Expo '70 Time Capsule from the year 1970, buried under a monument near Osaka Castle, Japan is scheduled to be opened.",
          category: .technology),
    Event(time: "28 May 8113 CE",
          info: "The Crypt of Civilization, a time capsule located at Oglethorpe University in Atlanta, Georgia, is scheduled to be opened after being sealed before World War II.",
          category: .technology),
    Event(time: "10,000",
          info: "If a failure of the Wilkes Subglacial Basin \"ice plug\" in the next few centuries were to endanger the East Antarctic Ice Sheet, it would take up to this long to melt completely. Sea levels would rise 3 to 4 metres. One of the potential long-term effects of global warming, this is separate from the shorter-term threat of the West Antarctic Ice Sheet.",
          category: .geology),
    Event(time: "10,000",
          info: "The red supergiant star Antares will likely have exploded in a supernova. The explosion should be easily visible on Earth in daylight.",
          category: .astronomy),
    Event(time: "10,000",
          info: "Most probable estimated lifespan of technological civilization, according to Frank Drake's original formulation of the Drake equation.",
          category: .technology),
    Event(time: "10,000",
          info: "If globalization trends lead to panmixia, human genetic variation will no longer be regionalized, as the effective population size will equal the actual population size.",
          category: .biology),
    Event(time: "10,000",
          info: "Humanity has a 95% probability of being extinct by this date, according to Brandon Carter's formulation of the controversial Doomsday argument, which argues that half of the humans who will ever have lived have probably already been born.",
          category: .math),
    Event(time: "10,000",
          info: "Planned lifespan of the Long Now Foundation's several ongoing projects, including a 10,000-year clock known as the Clock of the Long Now, the Rosetta Project, and the Long Bet Project.",
          category: .technology),
    Event(time: "10,000",
          info: "Estimated lifespan of the HD-Rosetta analog disc, an ion beam-etched writing medium on nickel plate, a technology developed at Los Alamos National Laboratory and later commercialized. (The Rosetta Project uses this technology, named after the Rosetta Stone).",
          category: .technology),
    Event(time: "10,000",
          info: "Projected lifespan of Norway's Svalbard Global Seed Vault.",
          category: .biology),
    Event(time: "10,000",
          info: "The Waste Isolation Pilot Plant, for nuclear weapons waste, is planned to be protected until this time, with a \"Permanent Marker\" system designed to warn off visitors through both multiple languages (the six UN languages and Navajo) and through pictograms. The Human Interference Task Force has provided the theoretical basis for United States plans for future nuclear semiotics.",
          category: .physics),
    Event(time: "13,000",
          info: "By this point, halfway through the precessional cycle, Earth's axial tilt will be reversed, causing summer and winter to occur on opposite sides of Earth's orbit. This means that the seasons in the Northern Hemisphere, which experiences more pronounced seasonal variation due to a higher percentage of land, will be even more extreme, as it will be facing towards the Sun at Earth's perihelion and away from the Sun at aphelion.",
          category: .astronomy),
    Event(time: "15,000",
          info: "According to the Sahara pump theory, the precession of Earth's poles will move the North African Monsoon far enough north to convert the Sahara back into having a tropical climate, as it had 5,000–10,000 years ago.",
          category: .geology),
    Event(time: "16,900",
          info: "Voyager 1 passes within 3.5 light-years of Proxima Centauri.",
          category: .astronomy),
    Event(time: "17,000",
          info: "Best-guess recurrence rate for a \"civilization-threatening\" supervolcanic eruption large enough to spew 1,000 gigatonnes of pyroclastic material.",
          category: .geology),
    Event(time: "18,500",
          info: "Pioneer 11 passes within 3.4 light-years of Alpha Centauri.",
          category: .astronomy),
    Event(time: "20,000",
          info: "According to the glottochronology linguistic model of Morris Swadesh, future languages should retain just 1 out of 100 \"core vocabulary\" words on their Swadesh list compared to that of their current progenitors.",
          category: .technology),
    Event(time: "20,300",
          info: "Voyager 2 passes within 2.9 light-years of Alpha Centauri.",
          category: .astronomy),
    Event(time: "24,000",
          info: "The Chernobyl Exclusion Zone, the 2,600-square-kilometre (1,000 sq mi) area of Ukraine and Belarus left deserted by the 1986 Chernobyl disaster, will return to normal levels of radiation.",
          category: .physics),
    Event(time: "25,000",
          info: "The northern Martian polar ice cap could recede as Mars reaches a warming peak of the northern hemisphere during the c. 50,000-year perihelion precession aspect of its Milankovitch cycle.",
          category: .geology),
    Event(time: "25,000",
          info: "The Arecibo message, a collection of radio data transmitted on 16 November 1974, reaches the distance of its destination, the globular cluster Messier 13. This is the only interstellar radio message sent to such a distant region of the galaxy. There will be a 24-light-year shift in the cluster's position in the galaxy during the time it takes the message to reach it, but as the cluster is 168 light-years in diameter, the message will still reach its destination. Any reply will take at least another 25,000 years from the time of its transmission (assuming faster-than-light communication is impossible).",
          category: .astronomy),
    Event(time: "30,000",
          info: "Estimated supply lifespan of fission-based breeder reactor reserves, using known sources, assuming 2009 world energy consumption.",
          category: .geology),
    Event(time: "33,800",
          info: "Pioneer 10 passes within 3.4 light-years of Ross 248.",
          category: .astronomy),
    Event(time: "34,400",
          info: "Pioneer 10 passes within 3.4 light-years of Alpha Centauri.",
          category: .astronomy),
    Event(time: "36,000",
          info: "The small red dwarf Ross 248 will pass within 3.024 light-years of Earth, becoming the closest star to the Sun. It will recede after about 8,000 years, making first Alpha Centauri (again) and then Gliese 445 the nearest stars",
          category: .astronomy),
    Event(time: "42,200",
          info: "Voyager 2 passes within 1.7 light-years of Ross 248.",
          category: .astronomy),
    Event(time: "44,100",
          info: "Voyager 1 passes within 1.8 light-years of Gliese 445.",
          category: .astronomy),
    Event(time: "46,600",
          info: "Pioneer 11 passes within 1.9 light-years of Gliese 445.",
          category: .astronomy),
    Event(time: "50,000",
          info: "According to Berger and Loutre (2002), the current interglacial period will end, sending the Earth back into a glacial period of the current ice age, regardless of the effects of anthropogenic global warming. According to more recent studies however (2016), the effects of anthropogenic global warming may delay this otherwise expected glacial period by another 50,000 years, effectively skipping it.",
          category: .geology),
    Event(time: "50,000",
          info: "The Niagara Falls will have eroded away the remaining 32 km to Lake Erie, and will cease to exist.",
          category: .geology),
    Event(time: "50,000",
          info: "The many glacial lakes of the Canadian Shield will have been erased by post-glacial rebound and erosion.",
          category: .geology),
    Event(time: "50,000",
          info: "The length of the day used for astronomical timekeeping reaches about 86,401 SI seconds due to lunar tides decelerating the Earth's rotation. Under the present-day timekeeping system, either a leap second would need to be added to the clock every single day, or else by then, in order to compensate, the length of the day would have had to have been officially lengthened by one SI second.",
          category: .astronomy),
    Event(time: "50,000",
          info: "The KEO space time capsule, if it is launched, will reenter Earth's atmosphere.",
          category: .astronomy),
    Event(time: "50,000",
          info: "Estimated atmospheric lifetime of tetrafluoromethane, the most durable greenhouse gas.",
          category: .geology),
    Event(time: "60,000",
          info: "Estimated supply lifespan of fission-based light-water reactor reserves if it is possible to extract all the uranium from seawater, assuming 2009 world energy consumption.",
          category: .geology),
    Event(time: "90,300",
          info: "Pioneer 10 passes within 0.76 light-years of HIP 117795.",
          category: .astronomy),
    Event(time: "100,000",
          info: "The proper motion of stars across the celestial sphere, which results from their movement through the Milky Way, renders many of the constellations unrecognizable by someone used to today's configuration",
          category: .astronomy),
    Event(time: "100,000",
          info: "The hypergiant star VY Canis Majoris will likely have exploded in a supernova.",
          category: .astronomy),
    Event(time: "100,000",
          info: "Native North American earthworms, such as Megascolecidae, will have naturally spread north through the United States Upper Midwest to the Canada–US border, recovering from the Laurentide Ice Sheet glaciation (38°N to 49°N), assuming a migration rate of 10 metres per year. (However, humans have already introduced non-native invasive earthworms of North America on a much shorter timescale, causing a shock to the regional ecosystem.)",
          category: .biology),
    Event(time: "100,000+",
          info: "Time required to terraform Mars with an oxygen-rich breathable atmosphere, using only plants with solar efficiency comparable to the biosphere currently found on Earth.",
          category: .geology),
    Event(time: "> 100,000",
          info: "As one of the long-term effects of global warming, 10% of anthropogenic carbon dioxide will still remain in a stabilized atmosphere.",
          category: .geology),
    Event(time: "211,000",
          info: "Half-life of technetium-99, the most important long-lived fission product in uranium-derived nuclear waste.",
          category: .physics),
    Event(time: "250,000",
          info: "Lōʻihi, the youngest volcano in the Hawaiian–Emperor seamount chain, will rise above the surface of the ocean and become a new volcanic island.",
          category: .geology),
    Event(time: "250,000",
          info: "The estimated minimum time at which the spent plutonium stored at New Mexico's Waste Isolation Pilot Plant will cease to be radiologically lethal to humans.",
          category: .physics),
    Event(time: "c. 300,000",
          info: "At some point in the next few hundred thousand years, the Wolf–Rayet star WR 104 may explode in a supernova. There is a small chance WR 104 is spinning fast enough to produce a gamma-ray burst, and an even smaller chance that such a GRB could pose a threat to life on Earth.",
          category: .astronomy),
    Event(time: "306,100",
          info: "Voyager 1 passes within 1 light-year of TYC 3135-52-1.",
          category: .astronomy),
    Event(time: "492,300",
          info: "Voyager 1 passes within 1.3 light-years of HD 28343.",
          category: .astronomy),
    Event(time: "500,000",
          info: "Earth will likely have been hit by an asteroid of roughly 1 km in diameter, assuming that it cannot be averted.",
          category: .astronomy),
    Event(time: "500,000",
          info: "The rugged terrain of Badlands National Park in South Dakota will have eroded away completely.",
          category: .geology),
    Event(time: "800,000 to 8 million",
          info: "Low estimate of Pioneer 10 plaque lifespan, before the etching is destroyed by poorly-understood interstellar erosion processes.",
          category: .astronomy),
    Event(time: "1 million",
          info: "Meteor Crater, a large impact crater in Arizona considered the \"freshest\" of its kind, will have eroded away.",
          category: .geology),
    Event(time: "1 million",
          info: "Highest estimated time until the red supergiant star Betelgeuse explodes in a supernova. For at least a few months, the supernova will be visible on Earth in daylight. Studies suggest this supernova will occur within a million years, and perhaps even as little as the next 100,000 years.",
          category: .astronomy),
    Event(time: "1 million",
          info: "Desdemona and Cressida, moons of Uranus, will likely have collided.",
          category: .astronomy),
    Event(time: "1 million",
          info: "Estimated shortest time by which humanity could colonize our Milky Way galaxy and become capable of harnessing all the energy of the galaxy, assuming a velocity of 10% the speed of light.",
          category: .technology),
    Event(time: "1 million",
          info: "Estimated lifespan of Memory of Mankind (MOM) self storage-style repository in Hallstatt salt mine in Austria, which stores information on inscribed tablets of stoneware.",
          category: .technology),
    Event(time: "1 million",
          info: "Planned lifespan of the Human Document Project being developed at the University of Twente in the Netherlands.",
          category: .technology),
    Event(time: "1 million",
          info: "Current glass objects in the environment will be decomposed.",
          category: .geology),
    Event(time: "1 million",
          info: "Various public monuments composed of hard granite will have eroded one metre, in a moderate climate, assuming a rate of 1 Bubnoff unit (1 mm in 1,000 years, or ≈1 inch in 25,000 years).",
          category: .geology),
    Event(time: "1 million",
          info: "Without maintenance, the Great Pyramid of Giza will erode into unrecognizability.",
          category: .geology),
    Event(time: "1 million",
          info: "On the Moon, Neil Armstrong's \"one small step\" footprint at Tranquility Base will erode by this time, along with those left by all twelve Apollo moonwalkers, due to the accumulated effects of space weathering. (Normal erosion processes active on Earth are not present due to the Moon's almost complete lack of atmosphere.)",
          category: .geology),
    Event(time: "1.2 million",
          info: "Pioneer 11 comes within 3 light-years of Delta Scuti.",
          category: .astronomy),
    Event(time: "1.28 ± 0.05 million",
          info: "The star Gliese 710 will pass as close as 0.0676 parsecs—0.221 light-years (14,000 astronomical units) to the Sun before moving away. This will gravitationally perturb members of the Oort cloud, a halo of icy bodies orbiting at the edge of the Solar System, thereafter raising the likelihood of a cometary impact in the inner Solar System.",
          category: .astronomy),
    Event(time: "1.3 million",
          info: "Pioneer 10 comes within 1.5 light-years of HD 52456.",
          category: .astronomy),
    Event(time: "2 million",
          info: "Estimated time for the recovery of coral reef ecosystems from human-caused ocean acidification; the recovery of marine ecosystems after the acidification event that occurred about 65 million years ago took a similar length of time.",
          category: .biology),
    Event(time: "2 million",
          info: "Vertebrate species separated for this long will generally undergo allopatric speciation. Evolutionary biologist James W. Valentine predicted that if humanity has been dispersed among genetically isolated space colonies over this time, the galaxy will host an evolutionary radiation of multiple human species with a \"diversity of form and adaptation that would astound us\". This would be a natural process of isolated populations, unrelated to potential deliberate genetic enhancement technologies.",
          category: .biology),
    Event(time: "2 million",
          info: "Pioneer 10 passes near the bright star Aldebaran.",
          category: .astronomy),
    Event(time: "2+ million",
          info: "The Grand Canyon will erode further, deepening slightly, but principally widening into a broad valley surrounding the Colorado River.",
          category: .geology),
    Event(time: "2.7 million",
          info: "Average orbital half-life of current centaurs, that are unstable because of gravitational interaction of the several outer planets. See predictions for notable centaurs.",
          category: .astronomy),
    Event(time: "4 million",
          info: "Pioneer 11 passes near one of the stars in the constellation Aquila.",
          category: .astronomy),
    Event(time: "7.2 million",
          info: "Without maintenance, Mount Rushmore will erode into unrecognizability.",
          category: .geology),
    Event(time: "7.8 million",
          info: "Humanity has a 95% probability of being extinct by this date, according to J. Richard Gott's formulation of the controversial Doomsday argument.",
          category: .math),
    Event(time: "8 million",
          info: "The LAGEOS satellites' orbits will decay, and they will re-enter Earth's atmosphere, carrying with them a message to any far future descendants of humanity, and a map of the continents as they are expected to appear then.",
          category: .astronomy),
    Event(time: "10 million",
          info: "The widening East African Rift valley is flooded by the Red Sea, causing a new ocean basin to divide the continent of Africa and the African Plate into the newly formed Nubian Plate and the Somali Plate.",
          category: .geology),
    Event(time: "10 million",
          info: "Estimated time for full recovery of biodiversity after a potential Holocene extinction, if it were on the scale of the five previous major extinction events. Even without a mass extinction, by this time most current species will have disappeared through the background extinction rate, with many clades gradually evolving into new forms.",
          category: .biology),
    Event(time: "10 million to 1 billion",
          info: "Cupid and Belinda, moons of Uranus, will likely have collided.",
          category: .astronomy),
    Event(time: "15.7 million",
          info: "Half-life of iodine-129, the most durable long-lived fission product in uranium-derived nuclear waste.",
          category: .physics),
    Event(time: "25 million",
          info: "According to Christopher R. Scotese, the movement of the San Andreas Fault will cause the Gulf of California to flood into the Central Valley. This will form a new inland sea on the West Coast of North America.",
          category: .geology),
    Event(time: "50 million",
          info: "Maximum estimated time before the moon Phobos collides with Mars.",
          category: .astronomy),
    Event(time: "50 million",
          info: "According to Christopher R. Scotese, the movement of the San Andreas Fault will cause the current locations of Los Angeles and San Francisco to merge.[45] The Californian coast will begin to be subducted into the Aleutian Trench.",
          category: .geology),
    Event(time: "50 million",
          info: "Africa's collision with Eurasia closes the Mediterranean Basin and creates a mountain range similar to the Himalayas.",
          category: .geology),
    Event(time: "50 million",
          info: "The Appalachian Mountains peaks will largely erode away, weathering at 5.7 Bubnoff units, although topography will actually rise as regional valleys deepen at twice this rate.",
          category: .geology),
    Event(time: "50-60 million",
          info: "The Canadian Rockies will erode away to a plain, assuming a rate of 60 Bubnoff units. The Southern Rockies in the United States are eroding at a somewhat slower rate.",
          category: .geology),
    Event(time: "50-400 million",
          info: "Estimated time for Earth to naturally replenish its fossil fuel reserves.",
          category: .geology),
    Event(time: "60 million",
          info: "Estimated supply lifespan of fusion power reserves if it is possible to extract all the lithium from seawater, assuming 1995 world energy consumption.",
          category: .geology),
    Event(time: "80 million",
          info: "The Big Island will have become the last of the current Hawaiian Islands to sink beneath the surface of the ocean, while a more recently formed chain of \"new Hawaiian Islands\" will then have emerged in their place.",
          category: .geology),
    Event(time: "100 million",
          info: "Earth will likely have been hit by an asteroid comparable in size to the one that triggered the K–Pg extinction 66 million years ago, assuming this cannot be averted.",
          category: .astronomy),
    Event(time: "100 million",
          info: "According to the Pangaea Proxima Model created by Christopher R. Scotese, a new subduction zone will open in the Atlantic Ocean and the Americas will begin to converge back toward Africa.",
          category: .geology),
    Event(time: "100 million",
          info: "Upper estimate for lifespan of the rings of Saturn in their current state.",
          category: .geology),
    Event(time: "100 million",
          info: "Maximal estimated lifespan of technological civilization, according to Frank Drake's original formulation of the Drake equation.",
          category: .technology),
    Event(time: "100 million",
          info: "Future archaeologists should be able to identify an \"Urban Stratum\" of fossilized great coastal cities, mostly through the remains of underground infrastructure such as building foundations and utility tunnels.",
          category: .geology),
    Event(time: "110 million",
          info: "The Sun's luminosity has increased by 1%.",
          category: .astronomy),
    Event(time: "180 million",
          info: "Due to the gradual slowing down of Earth's rotation, a day on Earth will be one hour longer than it is today.",
          category: .astronomy),
    Event(time: "230 million",
          info: "Prediction of the orbits of the planets is impossible over greater time spans than this, due to the limitations of Lyapunov time.",
          category: .math),
    Event(time: "240 million",
          info: "From its present position, the Solar System completes one full orbit of the Galactic Center.",
          category: .astronomy),
    Event(time: "250 million",
          info: "According to Christopher R. Scotese, due to the northward movement of the West Coast of North America, the coast of California will collide with Alaska.",
          category: .geology),
    Event(time: "250-300 million",
          info: "All the continents on Earth may fuse into a supercontinent. Three potential arrangements of this configuration have been dubbed Amasia, Novopangaea, and Pangaea Ultima. This will likely result in a glacial period, lowering sea levels and increasing oxygen levels, further lowering global temperatures.",
          category: .geology),
    Event(time: "> 250 million",
          info: "Rapid biological evolution may occur due to the formation of a supercontinent causing lower temperatures and higher oxygen levels. Increased competition between species due to the formation of a supercontinent, increased volcanic activity and less hospitable conditions due to global warming from a brighter Sun could result in a mass extinction event from which plant and animal life may not fully recover.",
          category: .biology),
    Event(time: "292,278,994 CE",
          info: "Numeric overflow in system time for Java computer programs.",
          category: .technology),
    Event(time: "300 million",
          info: "Due to a shift in the equatorial Hadley cells to roughly 40° north and south, the amount of arid land will increase by 25%.",
          category: .geology),
    Event(time: "300-600 million",
          info: "Estimated time for Venus's mantle temperature to reach its maximum. Then, over a period of about 100 million years, major subduction occurs and the crust is recycled.",
          category: .geology),
    Event(time: "350 million",
          info: "According to the extroversion model first developed by Paul F. Hoffman, subduction ceases in the Pacific Ocean Basin.",
          category: .geology),
    Event(time: "400-500 million",
          info: "The supercontinent (Pangaea Ultima, Novopangaea, or Amasia) will likely have rifted apart. This will likely result in higher global temperatures, similar to the Cretaceous period.",
          category: .geology),
    Event(time: "500 million",
          info: "Estimated time until a gamma-ray burst, or massive, hyperenergetic supernova, occurs within 6,500 light-years of Earth; close enough for its rays to affect Earth's ozone layer and potentially trigger a mass extinction, assuming the hypothesis is correct that a previous such explosion triggered the Ordovician–Silurian extinction event. However, the supernova would have to be precisely oriented relative to Earth to have any such effect.",
          category: .astronomy),
    Event(time: "600 million",
          info: "Tidal acceleration moves the Moon far enough from Earth that total solar eclipses are no longer possible.",
          category: .astronomy),
    Event(time: "500-600 million",
          info: "The Sun's increasing luminosity begins to disrupt the carbonate–silicate cycle; higher luminosity increases weathering of surface rocks, which traps carbon dioxide in the ground as carbonate. As water evaporates from the Earth's surface, rocks harden, causing plate tectonics to slow and eventually stop once the oceans evaporate completely. With less volcanism to recycle carbon into the Earth's atmosphere, carbon dioxide levels begin to fall. By this time, carbon dioxide levels will fall to the point at which C3 photosynthesis is no longer possible. All plants that utilize C3 photosynthesis (≈99 percent of present-day species) will die. The extinction of C3 plant life is likely to be a long-term decline rather than a sharp drop. It is likely that plant groups will die one by one well before the critical carbon dioxide level is reached. The first plants to disappear will be C3 herbaceous plants, followed by deciduous forests, evergreen broad-leaf forests and finally evergreen conifers.",
          category: .geology),
    Event(time: "500-800 million",
          info: "As Earth begins to rapidly warm and carbon dioxide levels fall, plants—and, by extension, animals—could survive longer by evolving other strategies such as requiring less carbon dioxide for photosynthetic processes, becoming carnivorous, adapting to desiccation, or associating with fungi. These adaptations are likely to appear near the beginning of the moist greenhouse. The death of most plant life will result in less oxygen in the atmosphere, allowing for more DNA-damaging ultraviolet radiation to reach the surface. The rising temperatures will increase chemical reactions in the atmosphere, further lowering oxygen levels. Flying animals would be better off because of their ability to travel large distances looking for cooler temperatures. Many animals may be driven to the poles or possibly underground. These creatures would become active during the polar night and aestivate during the polar day due to the intense heat and radiation. Much of the land would become a barren desert, and plants and animals would primarily be found in the oceans.",
          category: .biology),
    Event(time: "800-900 million",
          info: "Carbon dioxide levels fall to the point at which C4 photosynthesis is no longer possible. Without plant life to recycle oxygen in the atmosphere, free oxygen and the ozone layer will disappear from the atmosphere allowing for intense levels of deadly UV light to reach the surface. In the book The Life and Death of Planet Earth, authors Peter D. Ward and Donald Brownlee state that some animal life may be able to survive in the oceans. Eventually, however, all multicellular life will die out. At most, animal life could survive about 100 million years after plant life dies out, with the last animals being animals that do not depend on living plants such as termites or those near hydrothermal vents such as worms of the genus Riftia. The only life left on the Earth after this will be single-celled organisms.",
          category: .biology),
    Event(time: "1 billion",
          info: "27% of the ocean's mass will have been subducted into the mantle. If this were to continue uninterrupted, it would reach an equilibrium where 65% of present-day surface water would be subducted.",
          category: .geology),
    Event(time: "1 billion",
          info: "Estimated time for an astroengineering project to alter the Earth's orbit, compensating for the Sun's rising brightness and outward migration of the habitable zone, accomplished by repeated asteroid gravity assists.",
          category: .astronomy),
    Event(time: "1 billion",
          info: "Estimated lifespan of the two Voyager Golden Records, before the information stored on them is rendered unrecoverable.",
          category: .astronomy),
    Event(time: "1 billion",
          info: "Estimated lifespan of \"Nanoshuttle memory device\" using an iron nanoparticle moved as a molecular switch through a carbon nanotube, a technology developed at the University of California at Berkeley.",
          category: .technology),
    Event(time: "1.1 billion",
          info: "The Sun's luminosity has risen by 10%, causing Earth's surface temperatures to reach an average of around 320 K (47 °C; 116 °F). The atmosphere will become a \"moist greenhouse\", resulting in a runaway evaporation of the oceans. This would cause plate tectonics to stop completely, if not already stopped before this time. Pockets of water may still be present at the poles, allowing abodes for simple life.",
          category: .geology),
    Event(time: "1.2 billion",
          info: "High estimate until all plant life dies out, assuming some form of photosynthesis is possible despite extremely low carbon dioxide levels. If this is possible, rising temperatures will make any animal life unsustainable from this point on.",
          category: .biology),
    Event(time: "1.3 billion",
          info: "Eukaryotic life dies out on Earth due to carbon dioxide starvation. Only prokaryotes remain.",
          category: .biology),
    Event(time: "1.5-1.6 billion",
          info: "The Sun's rising luminosity causes its circumstellar habitable zone to move outwards; as carbon dioxide rises in Mars's atmosphere, its surface temperature rises to levels akin to Earth during the ice age.",
          category: .astronomy),
    Event(time: "1.6 billion",
          info: "Lower estimate until all prokaryotic life will go extinct.",
          category: .biology),
    Event(time: "2 billion",
           info: "High estimate until the Earth's oceans evaporate if the atmospheric pressure were to decrease via the nitrogen cycle.",
           category: .geology),
    Event(time: "2.3 billion",
          info: "The Earth's outer core freezes if the inner core continues to grow at its current rate of 1 mm (0.039 in) per year. Without its liquid outer core, the Earth's magnetic field shuts down, and charged particles emanating from the Sun gradually deplete the atmosphere.",
          category: .geology),
    Event(time: "2.55 billion",
          info: "The Sun will have reached a maximum surface temperature of 5,820 K. From then on, it will become gradually cooler while its luminosity will continue to increase.",
          category: .astronomy),
    Event(time: "2.8 billion",
          info: "Earth's surface temperature reaches around 420 K (147 °C; 296 °F), even at the poles.",
          category: .geology),
    Event(time: "2.8 billion",
          info: "All life, which by now had been reduced to unicellular colonies in isolated, scattered microenvironments such as high-altitude lakes or caves, goes extinct.",
          category: .biology),
    Event(time: "c. 3 billion",
          info: "There is a roughly 1-in-100,000 chance that the Earth might be ejected into interstellar space by a stellar encounter before this point, and a 1-in-3-million chance that it will then be captured by another star. Were this to happen, life, assuming it survived the interstellar journey, could potentially continue for far longer.",
          category: .astronomy),
    Event(time: "3 billion",
          info: "Median point at which the Moon's increasing distance from the Earth lessens its stabilising effect on the Earth's axial tilt. As a consequence, Earth's true polar wander becomes chaotic and extreme, leading to dramatic shifts in the planet's climate due to the changing axial tilt.",
          category: .astronomy),
    Event(time: "3.3 billion",
          info: "1% chance that Jupiter's gravity may make Mercury's orbit so eccentric as to collide with Venus, sending the inner Solar System into chaos. Possible scenarios include Mercury colliding with the Sun, being ejected from the Solar System, or colliding with Earth.",
          category: .astronomy),
    Event(time: "3.5-4.5 billion",
          info: "All water currently present in oceans (if not lost earlier) evaporates. The greenhouse effect caused by the massive, water-rich atmosphere, combined with the Sun's luminosity reaching roughly 35–40% above its present value, will result in Earth's surface temperature rising to 1,400 K (1,130 °C; 2,060 °F)—hot enough to melt some surface rock. This period in Earth's future is often compared to Venus today, but the temperature is actually around two times the temperature on Venus today, and at this temperature the surface will be partially molten, while Venus probably has a mostly solid surface at present. Venus will also probably drastically heat up at this time as well, most likely being much hotter than Earth will be (as it is closer to the Sun).",
          category: .geology),
    Event(time: "3.6 billion",
          info: "Neptune's moon Triton falls through the planet's Roche limit, potentially disintegrating into a planetary ring system similar to Saturn's.",
          category: .astronomy),
    Event(time: "4 billion",
          info: "Median point by which the Andromeda Galaxy will have collided with the Milky Way, which will thereafter merge to form a galaxy dubbed \"Milkomeda\". There is also a small chance of the Solar System being ejected. The planets of the Solar System will almost certainly not be disturbed by these events.",
          category: .astronomy),
    Event(time: "4.5 billion",
          info: "Mars reaches the same solar flux the Earth did when it first formed, 4.5 billion years ago from today.",
          category: .geology),
    Event(time: "5 billion",
          info: "Estimated supply lifespan of fission-based breeder reactor reserves if it is possible to extract all the uranium from seawater, assuming 1983 world energy consumption.",
          category: .geology),
    Event(time: "5.4 billion",
          info: "With the hydrogen supply exhausted at its core, the Sun leaves the main sequence and begins to evolve into a red giant.",
          category: .astronomy),
    Event(time: "6.5 billion",
          info: "Mars reaches the same solar radiation flux as Earth today, after which it will suffer a similar fate to the Earth as described above.",
          category: .geology),
    Event(time: "7.5 billion",
          info: "Earth and Mars may become tidally locked with the expanding subgiant Sun.",
          category: .astronomy),
    Event(time: "7.59 billion",
          info: "The Earth and Moon are very likely destroyed by falling into the Sun, just before the Sun reaches the tip of its red giant phase and its maximum radius of 256 times the present-day value. Before the final collision, the Moon possibly spirals below Earth's Roche limit, breaking into a ring of debris, most of which falls to the Earth's surface.",
          category: .astronomy),
    Event(time: "7.59 billion",
          info: "During this era, Saturn's moon Titan may reach surface temperatures necessary to support life.",
          category: .astronomy),
    Event(time: "7.9 billion",
          info: "The Sun reaches the tip of the red-giant branch of the Hertzsprung–Russell diagram, achieving its maximum radius of 256 times the present-day value. In the process, Mercury, Venus, and very likely Earth are destroyed.",
          category: .astronomy),
    Event(time: "8 billion",
          info: "The Sun becomes a carbon–oxygen white dwarf with about 54.05% its present mass. At this point, if somehow the Earth survives, temperatures on the surface of the planet, as well as other remaining planets in the Solar System, will begin dropping rapidly, due to the white dwarf Sun emitting much less energy than it does today.",
          category: .astronomy),
    Event(time: "> 13 billion",
          info: "Estimated lifespan of \"Superman memory crystal\" data storage using femtosecond laser-etched nanostructures in glass, a technology developed at the University of Southampton.",
          category: .technology),
    Event(time: "22 billion",
          info: "The end of the Universe in the Big Rip scenario, assuming a model of dark energy with w = −1.5. If the density of dark energy is less than −1, then the Universe's expansion would continue to accelerate and the Observable Universe would continue to get smaller. Around 200 million years before the Big Rip, galaxy clusters like the Local Group or the Sculptor Group would be destroyed. Sixty million years before the Big Rip, all galaxies will begin to lose stars around their edges and will completely disintegrate in another 40 million years. Three months before the Big Rip, all star systems will become gravitationally unbound, and planets will fly off into the rapidly expanding universe. Thirty minutes before the Big Rip, planets, stars, asteroids and even extreme objects like neutron stars and black holes will evaporate into atoms. One hundred zeptoseconds (10−19 seconds) before the Big Rip, atoms would break apart. Ultimately, once rip reaches the Planck scale, cosmic strings would be disintegrated as well as the fabric of spacetime itself. The universe would enter into a \"rip singularity\" when all distances become infinitely large. Whereas in a \"crunch singularity\" all matter is infinitely concentrated, in a \"rip singularity\" all matter is infinitely spread out. However, observations of galaxy cluster speeds by the Chandra X-ray Observatory suggest that the true value of w is c. −0.991, meaning the Big Rip will not occur.",
          category: .astronomy),
    Event(time: "50 billion",
          info: "If the Earth and Moon are not engulfed by the Sun, by this time they will become tidelocked, with each showing only one face to the other. Thereafter, the tidal action of the white dwarf Sun will extract angular momentum from the system, causing the lunar orbit to decay and the Earth's spin to accelerate.",
          category: .astronomy),
    Event(time: "65 billion",
          info: "The Moon may end up colliding with the Earth due to the decay of its orbit, assuming the Earth and Moon are not engulfed by the red giant Sun.",
          category: .astronomy),
    Event(time: "100-150 billion",
          info: "The Universe's expansion causes all galaxies beyond the former Milky Way's Local Group to disappear beyond the cosmic light horizon, removing them from the observable universe.",
          category: .astronomy),
    Event(time: "150 billion",
          info: "The cosmic microwave background cools from its current temperature of c. 2.7 K to 0.3 K, rendering it essentially undetectable with current technology.",
          category: .astronomy),
    Event(time: "150 billion",
          info: "Estimated supply lifespan of fusion power reserves if it is possible to extract all the deuterium from seawater, assuming 1995 world energy consumption.",
          category: .geology),
    Event(time: "292,277,026,596 CE",
          info: "Numeric overflow in system time for 64-bit Unix systems.",
          category: .technology),
    Event(time: "325 billion",
          info: "Estimated time by which the expansion of the universe isolates all gravitationally bound structures within their own cosmological horizon. At this point, the universe has expanded by a factor of more than 100 million, and even individual exiled stars are isolated.",
          category: .astronomy),
    Event(time: "450 billion",
          info: "Median point by which the c. 47 galaxies of the Local Group will coalesce into a single large galaxy.",
          category: .astronomy),
    Event(time: "800 billion",
          info: "Expected time when the net light emission from the combined \"Milkomeda\" galaxy begins to decline as the red dwarf stars pass through their blue dwarf stage of peak luminosity",
          category: .astronomy),
    Event(time: "1 trillion",
          info: "Low estimate for the time until star formation ends in galaxies as galaxies are depleted of the gas clouds they need to form stars.",
          category: .astronomy),
    Event(time: "1 trillion",
          info: "The Universe's expansion, assuming a constant dark energy density, multiplies the wavelength of the cosmic microwave background by 1029, exceeding the scale of the cosmic light horizon and rendering its evidence of the Big Bang undetectable. However, it may still be possible to determine the expansion of the universe through the study of hypervelocity stars.",
          category: .astronomy),
    Event(time: "1.05 trillion",
          info: "Estimated time by which the Universe will have expanded by a factor of more than 1026, reducing the average particle density to less than one particle per cosmological horizon volume. Beyond this point, particles of unbound intergalactic matter are effectively isolated, and collisions between them cease to affect the future evolution of the Universe.",
          category: .astronomy),
    Event(time: "2 trillion",
          info: "Estimated time by which all objects beyond our Local Group are redshifted by a factor of more than 1053. Even the highest energy gamma rays are stretched so that their wavelength is greater than the physical diameter of the horizon.",
          category: .astronomy),
    Event(time: "4 trillion",
          info: "Estimated time until the red dwarf star Proxima Centauri, the closest star to the Sun at a distance of 4.25 light-years, leaves the main sequence and becomes a white dwarf.",
          category: .astronomy),
    Event(time: "10 trillion",
          info: "Estimated time of peak habitability in the universe, unless habitability around low-mass stars is suppressed.",
          category: .astronomy),
    Event(time: "12 trillion",
          info: "Estimated time until the red dwarf VB 10, as of 2016 the least massive main sequence star with an estimated mass of 0.075 M☉, runs out of hydrogen in its core and becomes a white dwarf.",
          category: .astronomy),
    Event(time: "30 trillion",
          info: "Estimated time for stars (including the Sun) to undergo a close encounter with another star in local stellar neighborhoods. Whenever two stars (or stellar remnants) pass close to each other, their planets' orbits can be disrupted, potentially ejecting them from the system entirely. On average, the closer a planet's orbit to its parent star the longer it takes to be ejected in this manner, because it is gravitationally more tightly bound to the star.",
          category: .astronomy),
    Event(time: "100 trillion",
          info: "High estimate for the time by which normal star formation ends in galaxies. This marks the transition from the Stelliferous Era to the Degenerate Era; with no free hydrogen to form new stars, all remaining stars slowly exhaust their fuel and die. By this time, the universe will have expanded by a factor of approximately 10²⁵⁵⁴.",
          category: .astronomy),
    Event(time: "110-120 trillion",
          info: "Time by which all stars in the universe will have exhausted their fuel (the longest-lived stars, low-mass red dwarfs, have lifespans of roughly 10–20 trillion years). After this point, the stellar-mass objects remaining are stellar remnants (white dwarfs, neutron stars, black holes) and brown dwarfs.",
          category: .astronomy),
    Event(time: "110-120 trillion",
          info: "Collisions between brown dwarfs will create new red dwarfs on a marginal level: on average, about 100 stars will be shining in what was once the Milky Way. Collisions between stellar remnants will create occasional supernovae.",
          category: .astronomy),
    Event(time: "10¹⁵ (1 quadrillion)",
          info: "Estimated time until stellar close encounters detach all planets in star systems (including the Solar System) from their orbits.",
          category: .astronomy),
    Event(time: "10¹⁵ (1 quadrillion)",
          info: "By this point, the Sun will have cooled to 5 K.",
          category: .astronomy),
    Event(time: "10¹⁹ to 10²⁰ (10-100 quintillion)",
          info: "Estimated time until 90–99% of brown dwarfs and stellar remnants (including the Sun) are ejected from galaxies. When two objects pass close enough to each other, they exchange orbital energy, with lower-mass objects tending to gain energy. Through repeated encounters, the lower-mass objects can gain enough energy in this manner to be ejected from their galaxy. This process eventually causes the Milky Way to eject the majority of its brown dwarfs and stellar remnants.",
          category: .astronomy),
    Event(time: "10²⁰ (100 quintillion)",
          info: "Estimated time until the Earth collides with the black dwarf Sun due to the decay of its orbit via emission of gravitational radiation, if the Earth is not ejected from its orbit by a stellar encounter or engulfed by the Sun during its red giant phase.",
          category: .astronomy),
    Event(time: "10²⁰ (100 quintillion)",
          info: "Estimated timescale for the Pioneer and Voyager spacecraft to collide with a star (or stellar remnant).",
          category: .astronomy),
    Event(time: "10²³ (100 sextillion)",
          info: "Around this timescale most stellar remnants and other objects are ejected from the remains of their galactic cluster.",
          category: .astronomy),
    Event(time: "10³⁰",
          info: "Estimated time until those stellar remnants not ejected from galaxies (1–10%) fall into their galaxies' central supermassive black holes. By this point, with binary stars having fallen into each other, and planets into their stars, via emission of gravitational radiation, only solitary objects (stellar remnants, brown dwarfs, ejected planetary-mass objects, black holes) will remain in the universe.",
          category: .astronomy),
    Event(time: "2×10³⁶",
          info: "Estimated time for all nucleons in the observable universe to decay, if the hypothesized proton half-life takes its smallest possible value (8.2×10³³ years).",
          category: .physics),
    Event(time: "3×10⁴³",
          info: "Estimated time for all nucleons in the observable universe to decay, if the hypothesized proton half-life takes the largest possible value, 1041 years, assuming that the Big Bang was inflationary and that the same process that made baryons predominate over anti-baryons in the early Universe makes protons decay. By this time, if protons do decay, the Black Hole Era, in which black holes are the only remaining celestial objects, begins.",
          category: .physics),
    Event(time: "10⁶⁵",
          info: "Assuming that protons do not decay, estimated time for rigid objects, from free-floating rocks in space to planets, to rearrange their atoms and molecules via quantum tunneling. On this timescale, any discrete body of matter \"behaves like a liquid\" and becomes a smooth sphere due to diffusion and gravity.",
          category: .physics),
    Event(time: "2×10⁶⁶",
          info: "Estimated time until a black hole of 1 solar mass decays into subatomic particles by Hawking radiation.",
          category: .physics),
    Event(time: "6×10⁹⁹",
          info: "Estimated time until the supermassive black hole of TON 618, as of 2018 the most massive known with a mass of 66 billion solar masses, dissipates by the emission of Hawking radiation, assuming zero angular momentum (that it does not rotate).",
          category: .physics),
    Event(time: "1.7×10¹⁰⁶",
          info: "Estimated time until a supermassive black hole with a mass of 20 trillion solar masses decays by Hawking radiation. This marks the end of the Black Hole Era. Beyond this time, if protons do decay, the Universe enters the Dark Era, in which all physical objects have decayed to subatomic particles, gradually winding down to their final energy state in the heat death of the universe.",
          category: .physics),
    Event(time: "10¹³⁹",
          info: "2018 estimate of Standard Model lifetime before collapse of a false vacuum; 95% confidence interval is 10⁵⁸ to 10²⁴¹ years due in part to uncertainty about the top quark mass.",
          category: .physics),
    Event(time: "10²⁰⁰",
          info: "Estimated high time for all nucleons in the observable universe to decay, if they do not via the above process, through any one of many different mechanisms allowed in modern particle physics (higher-order baryon non-conservation processes, virtual black holes, sphalerons, etc.) on time scales of 10⁴⁶ to 10²⁰⁰ years.",
          category: .physics),
    Event(time: "10¹¹⁰⁰ to 10³²⁰⁰⁰",
          info: "Estimated time for those black dwarfs with masses at or above 1.2 times the mass of the Sun to undergo supernovae as a result of slow silicon-nickel-iron fusion, as the declining electron fraction lowers their Chandrasekhar limit, assuming protons do not decay.",
          category: .physics),
    Event(time: "10¹⁵⁰⁰",
          info: "Assuming protons do not decay, the estimated time until all baryonic matter in stellar-mass objects has either fused together via muon-catalyzed fusion to form iron-56 or decayed from a higher mass element into iron-56 to form an iron star.",
          category: .physics),
    Event(time: "10^10^26",
          info: "Conservative estimate for the time until all iron stars collapse via quantum tunnelling into black holes, assuming no proton decay or virtual black holes.",
          category: .physics),
    Event(time: "10^10^26",
          info: "On this vast timescale, even ultra-stable iron stars will have been destroyed by quantum tunnelling events. First iron stars of sufficient mass (somewhere between 0.2 M☉ and the Chandrasekhar limit) will collapse via tunnelling into neutron stars. Subsequently, neutron stars and any remaining iron stars heavier than the Chandrasekhar limit collapse via tunnelling into black holes. The subsequent evaporation of each resulting black hole into subatomic particles (a process lasting roughly 10100 years), and subsequent shift to the Dark Era is on these timescales instantaneous.",
          category: .physics),
    Event(time: "10^10^50",
          info: "Estimated time for a Boltzmann brain to appear in the vacuum via a spontaneous entropy decrease.",
          category: .physics),
    Event(time: "10^10^76",
          info: "High estimate for the time until all iron stars collapse into black holes, assuming no proton decay or virtual black holes, which then (on these timescales) instantaneously evaporate into subatomic particles.",
          category: .physics),
    Event(time: "10^10^76",
          info: "This is also the highest estimate possible time for Black Hole Era (and subsequent Dark Era) to finally commence. Beyond this point, it is almost certain that Universe will contain no more baryonic matter and will be an almost pure vacuum (possibly accompanied with the presence of a false vacuum) until it reaches its final energy state, assuming it does not happen before this time.",
          category: .physics),
    Event(time: "10^10^120",
          info: "Highest estimate for the time it takes for the universe to reach its final energy state, even in the presence of a false vacuum.",
          category: .physics),
    Event(time: "10^10^10^56",
          info: "Time for quantum effects to generate a new Big Bang, resulting in a new universe. Around this vast timeframe, quantum tunnelling in any isolated patch of the now-empty universe could generate new inflationary events, resulting in new Big Bangs giving birth to new universes.",
          category: .physics),
    Event(time: "10^10^10^56",
          info: "Because the total number of ways in which all the subatomic particles in the observable universe can be combined is 10^10^115 a number which, when multiplied by 10^10^10^56, disappears into the rounding error, this is also the time required for a quantum-tunnelled and quantum fluctuation-generated Big Bang to produce a new universe identical to our own, assuming that every new universe contained at least the same number of subatomic particles and obeyed laws of physics within the landscape predicted by string theory",
          category: .physics)
]
